### ISSUE TITLE
Add a license

### ISSUE THREAD

**Issue by EKaroune** [thepolm3/phynd#1]
Hello Siggy and Joshua, I suggest that you add a license to tell other how they can reuse this material.

CC-BY 4.0 - more for documentation. See the webpage [here](https://creativecommons.org/about/cclicenses/)

And MIT license are probably needed - for code. - [license details here](https://opensource.org/licenses/MIT)

**Comment by thepolm3** [comment]
Good point -- I'll look at getting a ReadMe and license onliine tomorrow

**Comment by thepolm3** [comment]
License added, readme updated!
